
title: 授权微服务
type: kk/micro

services:
  Auth:
    title: 授权服务
    tasks:
      Create:
        title: 创建授权
        name: /auth/create
        input:
          - name: name
            type: string
            title: 授权名
          - name: uid
            type: long
            title: 用户ID
          - name: openid
            type: string
            title: 第三方用户ID
          - name: phone
            type: string
            title: 手机号
          - name: deviceId
            type: string
            title: 设备ID
          - name: expires
            type: long
            title: 超时秒数
          - name: options
            type: object
            title: 其他属性
        output:
          - name: auth
            title: 授权
            omitempty: true
            type: Auth
      Set:
        title: 修改授权
        name: /auth/set
        input:
          - name: code
            type: string
            title: 授权码
          - name: uid
            type: long
            title: 用户ID
          - name: openid
            type: string
            title: 第三方用户ID
          - name: phone
            type: string
            title: 手机号
          - name: deviceId
            type: string
            title: 设备ID
          - name: expires
            type: long
            title: 超时秒数
          - name: options
            type: object
            title: 其他属性
        output:
          - name: auth
            title: 授权
            omitempty: true
            type: Auth

      Get:
        title: 获取授权
        name: /auth/get
        input:
          - name: code
            type: string
            title: 授权代码
        output:
          - name: auth
            title: 授权
            omitempty: true
            type: Auth

      Remove:
        title: 删除授权
        name: /auth/remove
        input:
          - name: code
            type: string
            title: 授权代码
        output:
          - name: auth
            title: 授权
            omitempty: true
            type: Auth

objects:
  Auth:
    title: 授权表
    name: auth
    type: db
    fields:
      - name: name
        type: string
        length: 64
        index: asc
        title: 名称
      - name: code
        type: string
        length: 32
        index: asc
        title: 授权码
      - name: uid
        type: long
        title: 用户ID
      - name: openid
        type: string
        length: 128
        title: 第三方用户ID
      - name: phone
        type: string
        length: 64
        title: 手机号
      - name: deviceId
        type: string
        length: 64
        title: 设备ID
      - name: expires
        type: long
        title: 超时秒数
      - name: options
        type: object
        title: 其他属性
        omitempty: true
      - name: atime
        type: long
        title: 访问时间
      - name: ctime
        type: long
        title: 创建时间

