
title: 验证码
type: kk/micro
       
services:
  Captcha:
    title: 验证码
    tasks:
      Create:
        title: 创建
        name: create
        input:
          - name: code
            type: string
            title: 唯一代码
          - name: expires
            type: long
            title: 超时时间(秒)
          - name: length
            type: int
            title: 校验码长度
        output:
          - name: captcha
            title: 验证码
            omitempty: true
            type: Captcha
      Verify:
        title: 验证
        name: verify
        input:
          - name: code
            type: string
            title: 唯一代码
          - name: digits
            type: string
            title: 校验码
          - name: md5
            type: string
            title: MD5校验码
        output:
          - name: captcha
            title: 验证码
            omitempty: true
            type: Captcha
      Remove:
        title: 删除
        name: remove
        input:
          - name: code
            type: string
            title: 唯一代码
        output:
          - name: captcha
            title: 验证码
            omitempty: true
            type: Captcha

objects:
  Captcha:
    title: 授权表
    name: captcha
    type: db
    fields:
      - name: code
        type: string
        length: 32
        index: asc
        title: 唯一代码
      - name: digits
        type: string
        length: 32
        title: 校验码[0-9]
      - name: md5
        type: string
        length: 32
        title: MD5校验码
      - name: etime
        type: long
        title: 过期时间
      - name: ctime
        type: long
        title: 创建时间
