
title: TAG
type: kk/micro
       
objects:
  Tag:
    title: TAG
    name: tag
    type: db
    fields:
      - name: tag
        type: string
        length: 128
        title: 标签
        index: asc
      - name: eid
        type: long
        title: 实体ID
        index: asc
      - name: ctime
        type: long
        title: 创建时间
  Counter:
    title: 计数器
    name: tag_counter
    type: db
    fields:
      - name: tag
        type: string
        length: 128
        title: 标签
        index: asc
      - name: count
        type: int
        title: 实体数量
        